sudo: true
branches:
  only:
    - master
language: node_js
node_js:
  - "10"
install:
  - npm install
before_script:
  - git clone "https://godbmw:$GITHUB_TOKEN@github.com/dongyuanxin/notes.git" notes
script:
  - npm run check
  - ./deploy.sh
